[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.bcmath"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

cmd = "php artisan storage:link || true && php artisan serve --host=0.0.0.0 --port=$PORT"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
